#!/bin/bash


WGET_VERSION=$(wget --version | grep -oie "wget [0-9][0-9.]*" | head -n 1 | awk '{print $2}')
if [ -z "$WGET_VERSION" ]
then
WGET_VERSION=PARSE_ERROR
fi

WGET_USER_AGENT="wget/$WGET_VERSION/esg/4.3.3-20230418-211618/created/2023-04-27T06:43:35-06:00"


##############################################################################
#
# Climate Data Gateway download script
#
#
# Generated by: NCAR Climate Data Gateway
#
# Template version: 0.4.7-wget-checksum
#
#
# Your download selection includes data that might be secured using API Token based
# authentication. Therefore, this script can have your api-token. If you
# re-generate your API Token after you download this script, the download will
# fail. If that happens, you can either re-download this script or you can replace
# the old API Token with the new one by going to the Account Home:
#
# https://www.earthsystemgrid.org/account/user/account-home.html
#
# and clicking on "API Token" link under "Personal Account". You will be asked
# to log into the application before you can view your API Token.
#
#
# Dataset
# isabeldata
# fceb1558-b745-11e6-a8e6-00c0f03d5b7c
# https://www.earthsystemgrid.org/dataset/isabeldata.html
# https://www.earthsystemgrid.org/dataset/id/fceb1558-b745-11e6-a8e6-00c0f03d5b7c.html
#
# Dataset Version
# Temporary Version
# fcebb199-b745-11e6-a8e6-00c0f03d5b7c
# https://www.earthsystemgrid.org/dataset/isabeldata/version/Temporary Version.html
# https://www.earthsystemgrid.org/dataset/version/id/fcebb199-b745-11e6-a8e6-00c0f03d5b7c.html
#
##############################################################################

CACHE_FILE=.md5_results
MAX_RETRY=3


usage() {
    echo "Usage: $(basename $0) [flags]"
    echo "Flags is one of:"

}
#defaults
debug=0
clean_work=1
verbose=1

#parse flags

while getopts ':pdvqko:' OPT; do

    case $OPT in

        p) clean_work=0;;       #	: preserve data that failed checksum
        o) output="$OPTARG";;   #<file>	: Write output for DML in the given file
        d) debug=1;;            #	: display debug information
        v) verbose=1;;          #       : be more verbose
        q) quiet=1;;            #	: be less verbose
        k) cert=1;;            #	: add --no-check-certificate
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

if [[ "$output" ]]; then
    #check and prepare the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    : > "$output" || { echo "Can't write file $output"; break; }
fi

    ((debug)) && echo "debug=$debug, cert=$cert, verbose=$verbose, quiet=$quiet, clean_work=$clean_work"

##############################################################################


check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum

    case $chk_type in
        md5) local_chksum=$(md5sum "$file" | cut -f1 -d" ");;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value"
    diff -q <(echo $local_chksum) <(echo $chk_value) >/dev/null
}

download() {

    if [[ "$cert" ]]; then
      wget="wget --no-check-certificate -c --user-agent=$WGET_USER_AGENT"
    else
      wget="wget -c --user-agent=$WGET_USER_AGENT"
    fi

    ((quiet)) && wget="$wget -q" || { ((!verbose)) && wget="$wget -nv"; }

    ((debug)) && echo "wget command: $wget"

    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #are we just writing a file?
        if [ "$output" ]; then
            echo "$file - $url" >> $output
            echo ""
            continue
        fi

        retry_counter=0

        while : ; do
                #if we have the file, check if it's already processed.
                [ -f "$file" ] && cached="$(grep $file $CACHE_FILE)" || unset cached

                #check it wasn't modified
                if [[ -n "$cached" && "$(stat -c %Y $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    echo "Already downloaded and verified"
                    break
                fi

                # (if we had the file size, we could check before trying to complete)
                echo "Downloading"
                $wget -O "$file" $url || { failed=1; break; }

                #check if file is there
                if [[ -f "$file" ]]; then
                        ((debug)) && echo file found
                        if ! check_chksum "$file" $chksum_type $chksum; then
                                echo "  $chksum_type failed!"
                                if ((clean_work)); then
                                        rm "$file"

                                        #try again up to n times
                                        echo -n "  Re-downloading..."

                                        if [ $retry_counter -eq $MAX_RETRY]
                                        then
                                            echo "  Re-tried file $file $MAX_RETRY times...."
                                            break
                                        fi
                                        retry_counter=`expr $retry_counter + 1`

                                        continue
                                else
                                        echo "  don't use -p or remove manually."
                                fi
                        else
                                echo "  $chksum_type ok. done!"
                                echo "$file" $(stat -c %Y "$file") $chksum >> $CACHE_FILE
                        fi
                fi
                #done!
                break
        done

        if ((failed)); then
            echo "download failed"

            unset failed
        fi

    done <<EOF--dataset.file.url.chksum_type.chksum
'HGTdata.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/HGTdata.bin.gz' 'md5' 'ad8b1d4fc155a5923db7e5dfe2aee37c'
'TCf01.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf01.bin.gz' 'md5' '385387f6e28ab134a487d50eee2a1c43'
'TCf02.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf02.bin.gz' 'md5' 'cf2aa9e8950d96b5841fd629a62a21ce'
'TCf03.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf03.bin.gz' 'md5' '46b9a25dd2b2066502b592193da2ad16'
'TCf04.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf04.bin.gz' 'md5' 'a5421693be3563457c463eed08679aa9'
'TCf05.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf05.bin.gz' 'md5' '152cf486ebc95f5965094da82997e9ef'
'TCf06.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf06.bin.gz' 'md5' '9b4c747c102e648b9c1a16104dc13563'
'TCf07.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf07.bin.gz' 'md5' 'ab07f10e24af662dc94752b72329e92f'
'TCf08.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf08.bin.gz' 'md5' '4928b87e0eec7b5a9bed523f1af8ddf8'
'TCf09.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf09.bin.gz' 'md5' 'b71bd31014f4df181631b5f855331a25'
'TCf10.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf10.bin.gz' 'md5' '66cc3fefce21fc9603785e2150e84c77'
'TCf11.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf11.bin.gz' 'md5' 'acdc08ad58c4ae146051b164e3c78658'
'TCf12.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf12.bin.gz' 'md5' '1107d0415f40a1ce41f1cb78cabc86d7'
'TCf13.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf13.bin.gz' 'md5' '1ecd1d19d29be3e7eb098c060c5a680c'
'TCf14.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf14.bin.gz' 'md5' 'a8acfa620d6aa633feed4b93aaffd723'
'TCf15.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf15.bin.gz' 'md5' '75a660fc72a248bd20b4b109a1dd628d'
'TCf16.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf16.bin.gz' 'md5' '3d627b9abbf03a42a31b697896edd949'
'TCf17.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf17.bin.gz' 'md5' 'beee2543a8decfd9f3fb2cd2eacf4981'
'TCf18.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf18.bin.gz' 'md5' '28f4f7e64b5c18a02d10aa7752c18ce8'
'TCf19.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf19.bin.gz' 'md5' 'c99b5227aa1af0a1193dff411ccbfaa9'
'TCf20.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf20.bin.gz' 'md5' '3909811130c5600c8d73965a46dbd315'
'TCf21.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf21.bin.gz' 'md5' '2984f116b4e8bd9b254a3678606bed77'
'TCf22.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf22.bin.gz' 'md5' '9f5a755e300e9a0f72971e9cc47a02f1'
'TCf23.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf23.bin.gz' 'md5' 'bae1e647dca02dff653575daa9781443'
'TCf24.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf24.bin.gz' 'md5' '11e7fd4b352589832d1581b1dbf35b31'
'TCf25.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf25.bin.gz' 'md5' 'f7153862afcc6ade37740e29513d22c3'
'TCf26.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf26.bin.gz' 'md5' '4d6f1bb7f1c781bc57f829de7fccd9f5'
'TCf27.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf27.bin.gz' 'md5' '6f96b773fa922f2bd1a0a37d11b10167'
'TCf28.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf28.bin.gz' 'md5' '5446b9902a5426e6b15fa02b34d62731'
'TCf29.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf29.bin.gz' 'md5' '67ce53458d481ed05ff40ee8d5582a10'
'TCf30.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf30.bin.gz' 'md5' 'a439840531fb6c8e8f8d8b7df8b3fb29'
'TCf31.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf31.bin.gz' 'md5' 'f5579f5fd949a8e2259d4e0d672d9c18'
'TCf32.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf32.bin.gz' 'md5' '3763bf937a8641f4c3f19590826264e2'
'TCf33.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf33.bin.gz' 'md5' 'cc62e92a4bbff2406e875403f146c8f7'
'TCf34.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf34.bin.gz' 'md5' 'fb308a4a560559bc98c215c830bff6e4'
'TCf35.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf35.bin.gz' 'md5' '5f8f1481918fd3ddeffede69d0a52a38'
'TCf36.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf36.bin.gz' 'md5' '8b220f0bc8ef7e025a840f5e07c7cc93'
'TCf37.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf37.bin.gz' 'md5' '7f87ee8b3c6f54f024d914b27b9489e8'
'TCf38.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf38.bin.gz' 'md5' '5c7bf39daf1469aba25be233c04e82b1'
'TCf39.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf39.bin.gz' 'md5' '08686ec027cc57d68f34d12ed0edc259'
'TCf40.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf40.bin.gz' 'md5' 'b4008f15d47c539f50dd0bddb176ba55'
'TCf41.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf41.bin.gz' 'md5' '0489425109a09e8c2068a119e5d05468'
'TCf42.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf42.bin.gz' 'md5' 'ec8e57d52d7244ca9e5cc549a75eaa57'
'TCf43.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf43.bin.gz' 'md5' 'd5cab3fc52ede969948bddd87f9a3003'
'TCf44.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf44.bin.gz' 'md5' 'dd9b5651b52bfbda1727413dd22f00d1'
'TCf45.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf45.bin.gz' 'md5' '4407a8e1f2fc2f1ebdd7d7babf934652'
'TCf46.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf46.bin.gz' 'md5' 'ac57f37eaca650a2da5b8fe5516af23f'
'TCf47.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf47.bin.gz' 'md5' '4130f472b31902b21f276443d04bf2c6'
'TCf48.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/TCf48.bin.gz' 'md5' 'e865129b1e0edc76a30e85a97e58e982'
'Uf01.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf01.bin.gz' 'md5' '9b44588ea2881c5cc86d4d49a06274f4'
'Uf02.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf02.bin.gz' 'md5' 'fb205beeef2b5d3b09caf4f7f753f429'
'Uf03.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf03.bin.gz' 'md5' '504d9ec986cb0f2e0249f1591ed6c9ac'
'Uf04.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf04.bin.gz' 'md5' 'f1a72659dc8cde1b3f0b2b44cc4c2c9f'
'Uf05.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf05.bin.gz' 'md5' '7a8d135f3da1a4df45122f210a045d76'
'Uf06.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf06.bin.gz' 'md5' 'e2d56d8e603806ee2ae312b554bad3c8'
'Uf07.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf07.bin.gz' 'md5' '8bad4adbd03926e8d79bb3dd08a4e5ba'
'Uf08.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf08.bin.gz' 'md5' '5e0351e4b282e3aecaa63a90e22662ba'
'Uf09.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf09.bin.gz' 'md5' '49dea11cc295310aa8805443e2808498'
'Uf10.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf10.bin.gz' 'md5' '08f370eba7ab4f5c57d9c767516518f9'
'Uf11.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf11.bin.gz' 'md5' 'dbb5a602ebb08e4f020389f78e59754e'
'Uf12.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf12.bin.gz' 'md5' '931c7437b41a945a957cbf7be2013ffa'
'Uf13.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf13.bin.gz' 'md5' '9cbc4df1f5ced186e3b43f9958b45800'
'Uf14.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf14.bin.gz' 'md5' 'fdb649132dd271f34d4f29a081de78f6'
'Uf15.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf15.bin.gz' 'md5' 'ec84da84a2b11097197df8f600cfea64'
'Uf16.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf16.bin.gz' 'md5' '5b9de627d78ccf399cd075730c39b43a'
'Uf17.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf17.bin.gz' 'md5' '7d4ae916d7b7f67d12a3d71e95c77092'
'Uf18.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf18.bin.gz' 'md5' '65bb521d281d55c2b9303410b6b4f67c'
'Uf19.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf19.bin.gz' 'md5' 'a55215d228c84b562ebee9d1287c5c12'
'Uf20.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf20.bin.gz' 'md5' '5e7a90ef59b251425fd896f9ca2fffaa'
'Uf21.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf21.bin.gz' 'md5' 'd596c76152d673d00a2d9c8f2fd2fc4b'
'Uf22.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf22.bin.gz' 'md5' '9bf641224d86980d6b98f1dbb7ac0135'
'Uf23.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf23.bin.gz' 'md5' '5a925e8af54418580b7187543c95ae48'
'Uf24.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf24.bin.gz' 'md5' '77a0e52090109ccd188c13cf057372d9'
'Uf25.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf25.bin.gz' 'md5' '172a7364f7238355c8cb2d9181101761'
'Uf26.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf26.bin.gz' 'md5' '2e3e8001d849211b2c026d3480edf4cc'
'Uf27.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf27.bin.gz' 'md5' '91bbe5f4b4298608b19125b9b44d12e4'
'Uf28.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf28.bin.gz' 'md5' '0e8ea17c52579dcbfdba95e1c495761d'
'Uf29.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf29.bin.gz' 'md5' '65b1304971ba3328793b18d07def8094'
'Uf30.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf30.bin.gz' 'md5' '8c915e8a8c9fad6d4ea4a36617830e6a'
'Uf31.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf31.bin.gz' 'md5' '196b24ea86171ed83bbcfd0c502336ee'
'Uf32.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf32.bin.gz' 'md5' '8b76ffcbc879d655d04aa4be5454eb3b'
'Uf33.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf33.bin.gz' 'md5' 'cc4615089995b82f02f3d13c39b36e7b'
'Uf34.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf34.bin.gz' 'md5' '1c9538b45d3e6932b38dbd67f61d4eb4'
'Uf35.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf35.bin.gz' 'md5' '166d9c06ecc25fdba1a90e26a5fa52c8'
'Uf36.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf36.bin.gz' 'md5' '4179a5682d76f67cbd47e6924cbec9a7'
'Uf37.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf37.bin.gz' 'md5' 'b6b23f77b6619d7ea54b902b481a0235'
'Uf38.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf38.bin.gz' 'md5' 'b47a67124de8e8eb51a42e74826a01a2'
'Uf39.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf39.bin.gz' 'md5' '53eebeb337652821098d052cec273e26'
'Uf40.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf40.bin.gz' 'md5' '1ee27cdd861fad89cfbb5e224c62cc68'
'Uf41.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf41.bin.gz' 'md5' '82ebe6a74fae28d9baf0b2ad8ed08cdd'
'Uf42.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf42.bin.gz' 'md5' 'c49edd460d9a4835206e0ebeec013df7'
'Uf43.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf43.bin.gz' 'md5' 'b2cde1c9003f6878160b27884e51570d'
'Uf44.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf44.bin.gz' 'md5' '23a9a344be97874bffc0179460bcba44'
'Uf45.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf45.bin.gz' 'md5' 'b41d9d8f1b0565a94a341c142ca2ac14'
'Uf46.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf46.bin.gz' 'md5' 'cfea35eab18409750727206c846caa31'
'Uf47.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf47.bin.gz' 'md5' '23e9f7b5e2693302ac14e1650155922d'
'Uf48.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Uf48.bin.gz' 'md5' '4e632164905c262df02c7eced8c647e9'
'Vf01.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf01.bin.gz' 'md5' 'aad6750975ecb6b341246be3a4c23dad'
'Vf02.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf02.bin.gz' 'md5' 'a5a8da0e4dd371eb0e4c2299a6c4c963'
'Vf03.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf03.bin.gz' 'md5' 'e24a9c9c79fd96254851041aa816ccd2'
'Vf04.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf04.bin.gz' 'md5' 'ff1047df96b9f0c21aa6826fd5cdd4c8'
'Vf05.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf05.bin.gz' 'md5' 'b69fbf77f30ddfec63cb3641690f4cde'
'Vf06.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf06.bin.gz' 'md5' 'b395cb5d993a9c933022d46b2d2acf97'
'Vf07.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf07.bin.gz' 'md5' '0bd05098b06ebe8c9dbf9ecdb704fd8f'
'Vf08.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf08.bin.gz' 'md5' '281e09b2e9727e7145525e2804f0442c'
'Vf09.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf09.bin.gz' 'md5' '0926607ee5e8178830e7692504f64ad7'
'Vf10.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf10.bin.gz' 'md5' '47b6e9d93c61d25ef35386d6336852cd'
'Vf11.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf11.bin.gz' 'md5' '2f58b31b9f8d4e7a43cbb69658207bae'
'Vf12.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf12.bin.gz' 'md5' 'cb31b59bdfe5ead6e439ece82d5dc5ea'
'Vf13.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf13.bin.gz' 'md5' '0b191a807b889fabf9aa411f999e62c4'
'Vf14.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf14.bin.gz' 'md5' '3851e90243c160f50c949e6f29177d18'
'Vf15.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf15.bin.gz' 'md5' '51db0de8fed4a4a184dffec3986c177e'
'Vf16.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf16.bin.gz' 'md5' '06269e014b4e868a5b73ffbcd40f1d8b'
'Vf17.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf17.bin.gz' 'md5' 'ffea48849f74734a58bc1b929a74bc65'
'Vf18.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf18.bin.gz' 'md5' 'ef491e424582b2927acdb2cdccfbb215'
'Vf19.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf19.bin.gz' 'md5' 'aa857b6c44024f713fed768ee1bbe4b3'
'Vf20.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf20.bin.gz' 'md5' '321429cb09a8034e9e22527c04c1b026'
'Vf21.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf21.bin.gz' 'md5' 'f76e668887fe123ebc4a39af8711742e'
'Vf22.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf22.bin.gz' 'md5' 'fc7a3e84df1ae8e9a95942c9f294e0e9'
'Vf23.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf23.bin.gz' 'md5' '8e93fc75d6f987fe9029e610fa2d998c'
'Vf24.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf24.bin.gz' 'md5' '318358239205de1a897edfa33387c109'
'Vf25.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf25.bin.gz' 'md5' 'cc198fa39c99a29dab82c223be8ce1bb'
'Vf26.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf26.bin.gz' 'md5' '9a082d88e162afeb82cea52f38910a11'
'Vf27.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf27.bin.gz' 'md5' '6e5c826658c08d0eb7b8b3615fd808a2'
'Vf28.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf28.bin.gz' 'md5' 'cb661b78c94129ac3efc7f086f2b0606'
'Vf29.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf29.bin.gz' 'md5' '7e7e18be98d1c0a99f6e8bf60f7acd3f'
'Vf30.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf30.bin.gz' 'md5' 'becbfd24c17915960c2a503ada4dec92'
'Vf31.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf31.bin.gz' 'md5' '1d0b04774a0607c18f9885a63ab8b0b0'
'Vf32.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf32.bin.gz' 'md5' 'cd0cf1ee202d078ce100dd2474027795'
'Vf33.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf33.bin.gz' 'md5' '909aceb348843676da0d7eae197606e6'
'Vf34.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf34.bin.gz' 'md5' 'aa99d5b81ad282e18dc0a11233fc5507'
'Vf35.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf35.bin.gz' 'md5' 'e9f8962970107621254d9ec1735cbf87'
'Vf36.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf36.bin.gz' 'md5' '7258e5bb3742bf561388e32c16be331a'
'Vf37.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf37.bin.gz' 'md5' '46bb91ad199aa3f572e4d6b2a4aa08c8'
'Vf38.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf38.bin.gz' 'md5' '9a743bde5b01dc20f3612747ef2d8c80'
'Vf39.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf39.bin.gz' 'md5' 'ae42465e575d5f66debd824aa4ffd521'
'Vf40.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf40.bin.gz' 'md5' '534f77d4dd10b6d5c69527454bd79afb'
'Vf41.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf41.bin.gz' 'md5' '307381b4770054e5a4cdb999433f69da'
'Vf42.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf42.bin.gz' 'md5' 'a2b40405b42fdde6c39f6453c8bc60f1'
'Vf43.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf43.bin.gz' 'md5' '9d4cd1c62c68b77093ef7449a326d27f'
'Vf44.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf44.bin.gz' 'md5' '70c8149ff34eaa31968ad2f9e5b6261f'
'Vf45.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf45.bin.gz' 'md5' '6889aa16b022652b2aee1bed67bc46a5'
'Vf46.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf46.bin.gz' 'md5' 'f201c0da953a21d0b16e11ef1e4bb659'
'Vf47.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf47.bin.gz' 'md5' 'f6a7ec2ca15a171c21a5c95483a59a3f'
'Vf48.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Vf48.bin.gz' 'md5' 'e5620a5a8e916c18a5753adf1e055e50'
'Wf01.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf01.bin.gz' 'md5' '6b43af59404a65f0ac65afe7174a3959'
'Wf02.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf02.bin.gz' 'md5' '4203800f0b6a82cd9b45041bcc33cb84'
'Wf03.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf03.bin.gz' 'md5' '94246eded4aaa725e1553ca2480c3982'
'Wf04.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf04.bin.gz' 'md5' '0c3261d90545fdb71b8092f42d3d853b'
'Wf05.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf05.bin.gz' 'md5' 'afa684e425a820a09dcb0affb903d444'
'Wf06.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf06.bin.gz' 'md5' '229b1398dc7fd6b9281fca306ce83ff3'
'Wf07.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf07.bin.gz' 'md5' '206b857e86238ce7accee0356aa13c54'
'Wf08.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf08.bin.gz' 'md5' 'af8914504eead81907543862925a5871'
'Wf09.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf09.bin.gz' 'md5' '6bb099f625a2c4f86946436437c4d4a2'
'Wf10.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf10.bin.gz' 'md5' 'b99cba8ca0175c2a3ba1f21488238b8a'
'Wf11.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf11.bin.gz' 'md5' '0843ff33743c2bd5839d1ed93c7b9fb7'
'Wf12.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf12.bin.gz' 'md5' '8bd34d3ab1374ecf9743e86dcd2b2b53'
'Wf13.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf13.bin.gz' 'md5' 'c95969fd61476bc6be93355b0fcbdd84'
'Wf14.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf14.bin.gz' 'md5' '443fe4a9b99acedeca0c7c98a909ec26'
'Wf15.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf15.bin.gz' 'md5' '7ade1b5f0e3a63ee39aa3a6b0ab300b3'
'Wf16.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf16.bin.gz' 'md5' '5261c4359365b9b77548df96d2a6580c'
'Wf17.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf17.bin.gz' 'md5' '139b512e144f16c535a3f1477ab0620c'
'Wf18.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf18.bin.gz' 'md5' '12f3833ce4fa55637f79d9665b749d0a'
'Wf19.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf19.bin.gz' 'md5' 'f228c75d0e317bdc71bd93dc4093e0b4'
'Wf20.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf20.bin.gz' 'md5' '98bfb709cecb4f1c66b84b6c64a91de4'
'Wf21.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf21.bin.gz' 'md5' '3d83d4620fcb48542bc733fc3708e7ed'
'Wf22.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf22.bin.gz' 'md5' '0cd55e26afedf6437eb11d7696a9e63d'
'Wf23.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf23.bin.gz' 'md5' '6b249c244f29e219f416f7c5533bc3f8'
'Wf24.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf24.bin.gz' 'md5' 'd2ef49fa6d8d3f8d904a827065555597'
'Wf25.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf25.bin.gz' 'md5' '1a15dd4caed057617fd7d08ce388bb27'
'Wf26.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf26.bin.gz' 'md5' '5816c6e09b5a0f024ec8f271610e93fc'
'Wf27.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf27.bin.gz' 'md5' '7e9c61571189de12e05e2697e3c68bdd'
'Wf28.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf28.bin.gz' 'md5' 'a08468cc83fff4307de59c9b0295fd36'
'Wf29.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf29.bin.gz' 'md5' '526fcd1da05103646edd7496eabc2e32'
'Wf30.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf30.bin.gz' 'md5' 'fea53b3d24f7fe7818fc4bbde58efab4'
'Wf31.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf31.bin.gz' 'md5' '0e8f188696130f576cb7cfe500c86459'
'Wf32.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf32.bin.gz' 'md5' 'b2d4d74d161d3dd14075de3d3f656dfb'
'Wf33.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf33.bin.gz' 'md5' 'ab30d90ee1f798916e9aad840497c119'
'Wf34.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf34.bin.gz' 'md5' '557ebf98b5c050b8a5a1e6fe7034f72f'
'Wf35.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf35.bin.gz' 'md5' 'e47fa3d4a0c74dab13a85cfb9c7efb2b'
'Wf36.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf36.bin.gz' 'md5' 'e8724de8a25d0bb93ec1f281996857a8'
'Wf37.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf37.bin.gz' 'md5' 'bd3d33038c54afe55e0696236b114682'
'Wf38.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf38.bin.gz' 'md5' 'cdd9322e3895ed4e8a684a6c6f49947b'
'Wf39.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf39.bin.gz' 'md5' 'e3ffa99f048dcf346aaba49f1ad6d97a'
'Wf40.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf40.bin.gz' 'md5' '7702cc282d736a2e5351302e7f5956fc'
'Wf41.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf41.bin.gz' 'md5' '44eaa9b5ab05cc70214ff232ac049f81'
'Wf42.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf42.bin.gz' 'md5' '9aa12a145f3e7b684d559a7add02c3f0'
'Wf43.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf43.bin.gz' 'md5' '5d111cd33440c27c4cf3484e986a3bff'
'Wf44.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf44.bin.gz' 'md5' 'afc23d2202541b7cfd3b82f97c10d8b3'
'Wf45.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf45.bin.gz' 'md5' '0e67aff456bcb94ac4fddd2d129132a6'
'Wf46.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf46.bin.gz' 'md5' '9a10998f48b9ccc5847283d1ea57c40a'
'Wf47.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf47.bin.gz' 'md5' '0b35f2545220bd07d5c630fd7f7cbb66'
'Wf48.bin.gz' 'https://www.earthsystemgrid.org/api/v1/dataset/isabeldata/file/Wf48.bin.gz' 'md5' '6c890c72a97f0949e0f474d3bff2895a'
EOF--dataset.file.url.chksum_type.chksum

}


#
# MAIN
#
echo "Running $(basename $0) version: $version"

#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE

download

#remove duplicates (if any)
{ rm $CACHE_FILE && tac | awk '!x[$1]++' | tac > $CACHE_FILE; } < $CACHE_FILE
